### ISSUE TITLE
Ensure params are indeed supposed to be dicts

### ISSUE THREAD

**Issue by chrisglass** [exoscale/raven#40]
When add-ring-request passes a request with params, sometimes sentry sees the paramas as "[object Object]".

We need to understand why.

**Comment by chrisglass** [comment]
Sentry expects entries in the env dict to be simple objects (not nested structures). So when passing params (which is a dict created by ring.middleware.params) sentry receives the json contents properly over the network, but the sentry UI tries to display the nested JSON dict, calling something silly like .toString() on it.

I think the solution here is for raven to detect the use of ring.middleware.params (that adds the :params entry to the request) and do the right thing for sentry to display it properly (probably, merge params with the env, or call (str) on it).

**Comment by greut** [comment]
Something like [ring.util.codec/form-encode](http://ring-clojure.github.io/ring-codec/ring.util.codec.html#var-form-encode) on the params could undo the `wrap-params` middleware.

**Comment by greut** [comment]
thanks for the investigation there!

**Comment by greut** [comment]
if sentry has the query-string key then params will duplicate it.

if the params contains the body, it's probably too big for sentry to deal with.

let's drop this?

**Comment by chrisglass** [comment]
New branch: https://github.com/exoscale/raven/pull/42
